// <auto-generated />
using MackMultiBot.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MackMultiBot.Database.Migrations
{
    [DbContext(typeof(BotDatabaseContext))]
    [Migration("20250215162821_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.2");

            modelBuilder.Entity("MackMultiBot.Database.Entities.LobbyConfiguration", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Mode")
                        .HasColumnType("INTEGER");

                    b.PrimitiveCollection<string>("Mods")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScoreMode")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("Size")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TeamMode")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LobbyConfigurations");
                });

            modelBuilder.Entity("MackMultiBot.Database.Entities.LobbyInstance", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("LobbyConfigurationId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("LobbyInstances");
                });
#pragma warning restore 612, 618
        }
    }
}
